---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features, on-premises ONTAP in NetApp Console 
summary: 今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。 
---
= NetApp ConsoleでオンプレミスのONTAPクラスタを管理する際の既知の制限
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。



== ASA r2 システムに関連する制限

NetApp ASA r2 システムを検出すると、System Manager に移動します。

ASA r2 システムでは他の管理オプションは利用できません。標準ビューを使用することはできず、 NetAppデータ サービスを有効にすることもできません。

https://docs.netapp.com/us-en/asa-r2/index.html["ASA r2システムの詳細"^]



== サポートされていないクラスター

SAML 認証が設定されているオンプレミスのONTAPクラスターは、コンソールではサポートされません。



== システムマネージャの制限

次の System Manager 機能はコンソールからはサポートされません。

* クラスターのセットアップ
+
オンプレミスのONTAPクラスターで管理 IP アドレスを設定し、管理者パスワードを構成すると、コンソールでクラスターを検出できるようになります。

* ロールベースのアクセス制御（コンソールエージェントのみ）
+
コンソール エージェントを使用してオンプレミスのONTAPクラスタを検出および管理する場合、System Manager からのロールベースのアクセス制御はサポートされません。検出プロセス中に管理者の資格情報を入力するよう求められます。これらの資格情報は、System Manager から実行されるすべてのアクションに使用されます。

+
直接検出オプションを使用すると、コンソールでシステムを開くたびに、 ONTAP認証情報を使用してログインするように求められます。

* NetApp Backup and Recoveryのアクティベーション
+
System Manager からのバックアップとリカバリを有効にするには、クラスターのバージョンが 9.13.1 である必要があります。

+
コンソール エージェントを使用してクラスターを検出しなかった場合、System Manager (詳細ビュー) を使用してバックアップとリカバリを有効にすることはできません。ただし、コンソールから直接オンプレミス クラスターでバックアップとリカバリを有効にすることができます。 https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["始める方法を学ぶ"^]

* オンデマンドアップグレード
+
クラスタ バージョンがONTAP 9.9.1 以前の場合、ファームウェアおよびソフトウェアのオンデマンド アップグレードは利用できません。

+
コンソール エージェントがない場合、ローカル マシンから更新することはできません。コンソールを使用してアクセスできるサーバーからのみ更新できます。

* グローバル検索
* ユーザーインターフェース設定

